/** Single source of truth for NJ tier-1 towns (metrics sourcing + merge). */

export const NJ_TIER1: Array<{ countySlug: string; townSlug: string; townName: string }> = [
  { countySlug: 'essex', townSlug: 'montclair', townName: 'Montclair' },
  { countySlug: 'hudson', townSlug: 'hoboken', townName: 'Hoboken' },
  { countySlug: 'mercer', townSlug: 'princeton', townName: 'Princeton' },
  { countySlug: 'bergen', townSlug: 'ridgewood', townName: 'Ridgewood' },
  { countySlug: 'bergen', townSlug: 'paramus', townName: 'Paramus' },
  { countySlug: 'union', townSlug: 'summit', townName: 'Summit' },
  { countySlug: 'union', townSlug: 'westfield', townName: 'Westfield' },
  { countySlug: 'morris', townSlug: 'morristown', townName: 'Morristown' },
  { countySlug: 'middlesex', townSlug: 'edison', townName: 'Edison' },
  { countySlug: 'camden', townSlug: 'cherry-hill', townName: 'Cherry Hill' },
  { countySlug: 'essex', townSlug: 'newark', townName: 'Newark' },
  { countySlug: 'hudson', townSlug: 'jersey-city', townName: 'Jersey City' },
  { countySlug: 'passaic', townSlug: 'paterson', townName: 'Paterson' },
  { countySlug: 'union', townSlug: 'elizabeth', townName: 'Elizabeth' },
  { countySlug: 'middlesex', townSlug: 'woodbridge', townName: 'Woodbridge' },
  { countySlug: 'ocean', townSlug: 'toms-river', townName: 'Toms River' },
  { countySlug: 'mercer', townSlug: 'hamilton', townName: 'Hamilton' },
  { countySlug: 'mercer', townSlug: 'trenton', townName: 'Trenton' },
  { countySlug: 'camden', townSlug: 'camden', townName: 'Camden' },
  { countySlug: 'ocean', townSlug: 'lakewood', townName: 'Lakewood Township' },
  { countySlug: 'monmouth', townSlug: 'middletown', townName: 'Middletown Township' },
  { countySlug: 'middlesex', townSlug: 'old-bridge', townName: 'Old Bridge Township' },
  { countySlug: 'middlesex', townSlug: 'east-brunswick', townName: 'East Brunswick' },
  { countySlug: 'somerset', townSlug: 'franklin', townName: 'Franklin Township' },
  { countySlug: 'somerset', townSlug: 'bridgewater', townName: 'Bridgewater Township' },
  { countySlug: 'passaic', townSlug: 'wayne', townName: 'Wayne Township' },
  { countySlug: 'essex', townSlug: 'east-orange', townName: 'East Orange' },
  { countySlug: 'hudson', townSlug: 'bayonne', townName: 'Bayonne' },
  { countySlug: 'middlesex', townSlug: 'piscataway', townName: 'Piscataway' },
]

export const PDF_DISTRICT_OVERRIDES: Record<string, string> = {
  Montclair: 'MONTCLAIR TWP',
  Hoboken: 'HOBOKEN CITY',
  Princeton: 'PRINCETON',
  Ridgewood: 'RIDGEWOOD VILLAGE',
  Paramus: 'PARAMUS BORO',
  Summit: 'SUMMIT CITY',
  Westfield: 'WESTFIELD TOWN',
  Morristown: 'MORRISTOWN TOWN',
  Edison: 'EDISON TWP',
  'Cherry Hill': 'CHERRY HILL TWNSHP',
  Newark: 'NEWARK CITY',
  'Jersey City': 'JERSEY CITY',
  Paterson: 'PATERSON CITY',
  Elizabeth: 'ELIZABETH CITY',
  Woodbridge: 'WOODBRIDGE TWP',
  'Toms River': 'TOMS RIVER TWP',
  Hamilton: 'HAMILTON TWP',
  Trenton: 'TRENTON CITY',
  Camden: 'CAMDEN CITY',
  'Lakewood Township': 'LAKEWOOD TWP',
  'Middletown Township': 'MIDDLETOWN TWP',
  'Old Bridge Township': 'OLD BRIDGE TWP',
  'East Brunswick': 'EAST BRUNSWICK TWP',
  'Franklin Township': 'FRANKLIN TWP',
  'Bridgewater Township': 'BRIDGEWATER TWP',
  'Wayne Township': 'WAYNE TWP',
  'East Orange': 'EAST ORANGE CITY',
  Bayonne: 'BAYONNE CITY',
  Piscataway: 'PISCATAWAY TWP',
}

export const NJ_TAXRATE_PDF_URL_TEMPLATE =
  'https://www.nj.gov/treasury/taxation/pdf/lpt/gtr/{year}taxrates.pdf'
export const NJ_GTR_SOURCE_REF = 'nj_div_taxation_general_effective_tax_rates'
